### ISSUE TITLE
Missing default value for window_size: TypeError: '<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by pjyi2147** [castorini/rank_llm#144]
Run end to end - RankZephyr command fails with error.

Command:
```
python src/rank_llm/scripts/run_rank_llm.py  --model_path=castorini/rank_zephyr_7b_v1_full --top_k_candidates=100 --dataset=dl20 \
--retrieval_method=SPLADE++_EnsembleDistil_ONNX --prompt_mode=rank_GPT  --context_size=4096 --variable_passages
```

Error:
```
Traceback (most recent call last):
  File "/home/tardis/patrickyi/rank_llm/src/rank_llm/scripts/run_rank_llm.py", line 180, in <module>
    main(args)
  File "/home/tardis/patrickyi/rank_llm/src/rank_llm/scripts/run_rank_llm.py", line 42, in main
    _ = retrieve_and_rerank(
  File "/home/tardis/patrickyi/rank_llm/src/rank_llm/retrieve_and_rerank.py", line 71, in retrieve_and_rerank
    rerank_results = reranker.rerank_batch(
  File "/home/tardis/patrickyi/rank_llm/src/rank_llm/rerank/reranker.py", line 51, in rerank_batch
    return self._agent.rerank_batch(
  File "/home/tardis/patrickyi/rank_llm/src/rank_llm/rerank/listwise/rank_listwise_os_llm.py", line 119, in rerank_batch
    window_size = min(window_size, top_k_retrieve)
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

I will push a PR with a fix setting a default value for `window_size` to 20 in `run_rank_llm.py`.

**Comment by pjyi2147** [comment]
Fixed with #145
