### ISSUE TITLE
ImportError: cannot import name 'IndexReader' from 'pyserini.index'

### ISSUE THREAD

**Issue by QianZ423** [castorini/rank_llm#158]
Hi,  I tried to execute the following command after configuring the rankllm Python environment according to the readme document, the error was as follows:

WARNING: Using incubator modules: jdk.incubator.vector
Traceback (most recent call last):
  File "/llm/base-model/rank_llm_model/rank_llm/src/rank_llm/scripts/run_rank_llm.py", line 13, in <module>
    from rank_llm.retrieve import TOPICS, RetrievalMethod, RetrievalMode
  File "/usr/local/miniconda/envs/rankllm2/lib/python3.10/site-packages/rank_llm/retrieve/__init__.py", line 2, in <module>
    from .pyserini_retriever import PyseriniRetriever, RetrievalMethod
  File "/usr/local/miniconda/envs/rankllm2/lib/python3.10/site-packages/rank_llm/retrieve/pyserini_retriever.py", line 7, in <module>
    from pyserini.index import IndexReader
ImportError: cannot import name 'IndexReader' from 'pyserini.index' (/usr/local/miniconda/envs/rankllm2/lib/python3.10/site-packages/pyserini/index/__init__.py)

The command to be executed is`python src/rank_llm/scripts/run_rank_llm.py  --model_path=castorini/rank_zephyr_7b_v1_full --top_k_candidates=100 --dataset=dl20 \
--retrieval_method=SPLADE++_EnsembleDistil_ONNX --prompt_mode=rank_GPT  --context_size=4096 --variable_passages`

The version of the pyserini package I installed is ’0.43.0‘

Thanks in advance!

**Comment by b8zhong** [comment]
IndexReader has been replaced with LuceneIndexReader in pyserini 0.43.0 - this PR has the fix, https://github.com/castorini/rank_llm/pull/156

Hope that helps!

**Comment by ronakice** [comment]
@QianZ423 can you check if the latest RankLLM from PyPI sorts this for you?

**Comment by ronakice** [comment]
Closing for now, let us know if you are still stuck!
